name: Playwright CI

on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      USERNAME: $ {{secrets.TEST_USERNAME}}
      PASSWORD: $ {{secrets.TEST_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start application
        run: nohup node app.js > app.log 2>&1 &

      - name: Run Playwright tests
        run: npx playwright test
